-- DO NOT EDIT THIS FILE; IT IS GENERATED FROM A SCRIPT
local wezterm = require('wezterm')
return {
  -- Weight: 3
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/abstract/1ub6r4ns7eopdsol.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/abstract/pexels-anni-roenkae-2156881.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/doom/doom-doom-slayer-4k-xm.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/doom/doom-ed-slayer-3h-1800x1169.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/doom/doom-vfr-5k-sg-1800x1169.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/doom/slayer_mark_neon.jpg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_hp_001.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_hp_002.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_hp_003.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_hp_004.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_lights_01.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/denver_lights_02.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/dk_signs.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/ny22_001.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/lar/ny22_002.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/ah_20220918a.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/ah_20230208.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/ah_20230216.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/ifly.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/linux_001.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/linux_002.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/van01.jpeg',
  wezterm.home_dir .. '/Dropbox/Library/T/terminal/wallpaper/photos/van02.jpeg',
}
