# vim: set ft=just ts=4 sw=4 sts=4 et ai si sta:

import 'users.just'
import 'mirror.just'

[default]
_list:
  just --list

# Remove SyncThing conflict files
[group('Maintenance')]
cleanup-syncthing:
  find . -name '*.sync-conflict-????????-??????-???????' -print -delete
