["bin/.diff-so-fancy"]
  type = "git-repo"
  url = "https://github.com/so-fancy/diff-so-fancy.git"
  refreshPeriod = "168h"
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"
# [".config/tmux/theme-tomorrow"]
#   type = "git-repo"
#   url = "https://github.com/edouard-lopez/tmux-tomorrow.git"
#   refreshPeriod = "720h"
[".config/tmux/theme-tomorrow"]
  type = "git-repo"
  url = "https://github.com/edouard-lopez/tmux-tomorrow.git"
  refreshPeriod = "720h"
[".config/base16-shell"]
  type = "git-repo"
  url = "https://github.com/tinted-theming/base16-shell.git"
  refreshPeriod = "720h"
[".scm_breeze"]
  type = "git-repo"
  url = "https://github.com/scmbreeze/scm_breeze.git"
  refreshPeriod = "168h"
