["bin/.diff-so-fancy"]
  type = "git-repo"
  url = "https://github.com/so-fancy/diff-so-fancy.git"
  refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"
[".config/tmux/theme-tomorrow"]
  type = "git-repo"
  url = "https://github.com/edouard-lopez/tmux-tomorrow.git"
  refreshPeriod = "720h"
[".config/base16-shell"]
  type = "git-repo"
  url = "https://github.com/tinted-theming/base16-shell.git"
  refreshPeriod = "720h"
[".scm_breeze"]
  type = "git-repo"
  url = "https://github.com/scmbreeze/scm_breeze.git"
  refreshPeriod = "168h"
[".config/antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote.git"
  refreshPeriod = "72h"
[".local/share/plex-nowplaying"]
  type = "git-repo"
  url = "https://github.com/arcadellama/plex-nowplaying.git"
  refreshPeriod = "720h"

### ncdu
{{ if eq "linux" .chezmoi.os }}
  {{ $ncduArch := .chezmoi.arch }}
  {{ if eq "amd64" .chezmoi.arch }}
  {{  $ncduArch = "x86_64" }}
  {{ end }}
  {{ $ncduVersion := "2.8.1" }}
  ["bin/ncdu"]
    type = "archive-file"
    url = "https://dev.yorhel.nl/download/ncdu-{{ $ncduVersion }}-linux-{{ $ncduArch }}.tar.gz"
    path = "ncdu"
{{ end }}
