add_prefix '+1', '👍'
add_prefix 'CALL', '☎'
add_prefix 'CAR', '🚕'
add_prefix 'CLEAN', '🧹'
add_prefix 'CODE', '💻'
add_prefix 'FEEL', '🧠'
add_prefix 'FOOD', '🍱'
add_prefix 'LEARN', '🧑‍🎓'
add_prefix 'LUNCH', '🍱 Lunch'
add_prefix 'MED', '💊'
add_prefix 'MEET', '👥'
add_prefix 'MEM', '📝'
add_prefix 'REST', '🍃 Rest'
add_prefix 'REVIEW', '🧐'
add_prefix 'SHOWER', '🚿 Shower'
add_prefix 'T', '✅'
add_prefix 'W', '⚒️'

