[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
# "github:ogham/exa" = "latest"
assh = "latest"
bat = "latest"
"github:aristocratos/btop" = { version = "latest", os = ["linux"] }
"cargo:ErebusBat/grcpass-rs" = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"github:mrkatebzadeh/darya" = "latest"
# glow = "latest"
jq = "latest"
jqp = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
"github:sst/opencode" = { version = "latest", os = ["linux"] }
restic = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
ruby = "4.0.3"
rust = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
"github:bahdotsh/mdterm" = "latest"
