[tools]
"github:Rigellute/spotify-tui" = "latest"
"github:Wilfred/difftastic" = "latest"
"github:eza-community/eza" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:moul/assh" = "latest"
