[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
# "github:ogham/exa" = "latest"
assh = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
jqp = "latest"
lazydocker = "latest"
lazygit = "latest"
restic = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
ruby = "3.4.5"
