[settings]
experimental = true

[tools]
"github:BurntSushi/ripgrep" = "latest"
"github:Rigellute/spotify-tui" = "latest"
"github:Wilfred/difftastic" = "latest"
"github:dandavison/delta" = "latest"
"github:eza-community/eza" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:muesli/duf" = "latest"
"github:ogham/exa" = "latest"
"github:sharkdp/bat" = "latest"
"github:twpayne/chezmoi" = "latest"
assh = "latest"
chezmoi = "latest"
fastfetch = "latest"
jq = "latest"
jqp = "latest"
restic = "latest"
ruby = "3.4.5"
