version = "1.0"

[defaults]
count = 10
template = "${hexrc} ${wordrc} ${wordrc} ${wordrc} ${wordrc} ${hexrc}"
format = "ruler"
wordlist = "/Users/andrew.burns/.local/share/xkp/words.db"

[providers.def]
hexrc = '${hex | upcase(chance=0.5)}'
wordrc = '${word | tcase(chance=0.25) | upcase(chance=0.25)}'

[providers.word]
min = 4

[providers.fwword]
min = 4

[providers.num]
min = 10
max = 99999

[providers.hex]
bytes = 4

[bootstrap]
allow_stemmed_imports = false
sources = [
    "/Users/andrew.burns/.local/share/hyph/",
    "/Users/andrew.burns/.local/share/wordlists/",
    "/Users/andrew.burns/.local/share/words/",
    "/Users/andrew.burns/.words/",
    "/usr/share/dict/",
    "/usr/share/dict/words",
    "/usr/share/dict/words.cap",
    "/usr/share/dict/upper",
    "/usr/share/dict/propernames",
    "/usr/share/dict/propers",
    "/usr/share/dict/propers/",
    "/usr/share/dict/wordlist/",
    "/usr/share/wordlists/",
    "/usr/share/seclists/Wordlists/",
    "/usr/share/seclists/",
]
