MYSERVER_PATH=$(HOME)/src/erebusbat/myserver/backrest/backrest/config
CFG_PATH=$(HOME)/.config/backrest

from_myserver:
	cp -v $(MYSERVER_PATH)/*.lst $(CFG_PATH)/

to_myserver:
	cp -v $(CFG_PATH)/*.lst $(MYSERVER_PATH)/
