onboarding = false

[ui]
show_agent_labels_on_pane_borders = true
[ui.toast]
delivery = "system"

[theme]
name = "dracula"
auto_switch = false

[keys]
prefix = "ctrl+a"
focus_pane_left = ["prefix+h", "ctrl+h"]
focus_pane_down = ["prefix+j", "ctrl+j"]
focus_pane_up = ["prefix+k", "ctrl+k"]
focus_pane_right = ["prefix+l", "ctrl+l"]
# previous_tab = "ctrl+alt+f10";  # prefix+P
# next_tab = "ctrl+alt+f11";      # prefix+N
last_pane = "prefix+;"
