onboarding = false

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "priority"
[ui.toast]
delivery = "herdr"

[experimental]
# allow_nested = true

[theme]
name = "dracula"
auto_switch = false

[keys]
prefix = "ctrl+a"
goto = "prefix+/"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
# WezTerm maps ⌘⇧[ => F10
previous_tab = ["prefix+p", "f10"]
# WezTerm maps ⌘⇧] => F11
next_tab = ["prefix+n", "f11"]
last_pane = "prefix+;"

############################################################
### vim-herdr-navigation
############################################################
[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "vim-herdr-navigation.left"
description = "navigate left (vim/herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "vim-herdr-navigation.down"
description = "navigate down (vim/herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "vim-herdr-navigation.up"
description = "navigate up (vim/herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "vim-herdr-navigation.right"
description = "navigate right (vim/herdr)"


############################################################
### herdr-navigator
############################################################
[[keys.command]]
key = "prefix+shift+s"
type = "plugin_action"
command = "herdr-navigator.open"
description = "jump to anything"

[[keys.command]]
key = "prefix+'"
type = "plugin_action"
command = "herdr-navigator.jump-back"
description = "jump to prevous workspace"
### END ####################################################
 
############################################################
### herdr-lazygit
############################################################
[[keys.command]]
key = "prefix+g"
type = "plugin_action"
command = "herdr-lazygit.open"

[[keys.command]]
key = "prefix+shift+g"
type = "plugin_action"
command = "herdr-lazygit.open-tab"

############################################################
### herdr-bar
############################################################
[[keys.command]]
key = "prefix+s"
type = "plugin_action"
command = "herdr-bar.open"
description = "command bar"

############################################################
### herdr-reviewr
############################################################
[[keys.command]]
key = "prefix+alt+r"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"
description = "toggle reviewer"
