# vim: set ft=just ts=4 sw=4 sts=4 et ai si sta:
HERDR_CMD := 'herdr'

# Check Config
[group('Config')]
check-config:
    {{ HERDR_CMD }} config check

# Reload Config
[group('Config')]
reload-config: check-config
    {{ HERDR_CMD }} server reload-config

# Add all config files to chezmoi
[group('Config')]
track-config: check-config track-config-no-check

[private]
track-config-no-check:
    chezmoi add \
        ./plugins/config/herdr-navigator/config.toml \
        ./config.toml ./justfile ./plugins.json             # Normal 'root' files
