section: screens
	dartp6:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none +bottom-left  +bottom-right
		switchCornerSize = 0
	USMB-JVK937H909:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	dartp6:
		down = USMB-JVK937H909
	USMB-JVK937H909:
		up = dartp6
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
	keystroke(shift+control+alt+super+F16) = switchToNextScreen
end
