# herdr-mirror host definitions
# https://github.com/nikok6/herdr-mirror

[hosts.outpost]
target = "outpost"
remote_bin = "~/.local/bin/herdr"

[hosts.maze]
target = "maze"
remote_bin = "~/.local/bin/herdr"

[hosts.nuc]
target = "nuc"
remote_bin = "~/.local/bin/herdr"

[hosts.dormouse]
target = "dormouse"
remote_bin = "~/.local/bin/herdr"
