# herdr-mirror host definitions
# https://github.com/nikok6/herdr-mirror

[hosts.outpost]
target = "outpost"
prefix = "🏰Outpost"
remote_bin = "~/.local/bin/herdr"

[hosts.maze]
target = "maze"
prefix = "🌽Maze"
remote_bin = "~/.local/bin/herdr"

[hosts.nuc]
target = "nuc"
prefix = "🍿nuc01"
remote_bin = "~/.local/bin/herdr"

[hosts.dormouse]
target = "dormouse"
prefix = "🐭dormouse"
remote_bin = "~/.local/bin/herdr"

[hosts.sys76]
target = "dartp6.lan"
prefix = "🧑‍💻sys76"
remote_bin = "~/.local/bin/herdr"
